algoritmo "2021-09-23 Exemplo - se número maior que 10"

// Disciplina  : UC05 - LP
// Professor   : Daniel Henrique
// Autor(a)    : Lucas Bortoli
// Data atual  : 23/09/2021

var
n: real

inicio

escreval("Digite um número: ")
escreva("> n = ")
leia(n)

escreval("")

se n > 10 entao
   escreval("O número é MAIOR que 10")
senao
   escreval("O número NÃO É maior que 10")
fimse

fimalgoritmo
